site_name: Klipper Dynamic Macros
site_url: https://3dcoded.github.io/DynamicMacros
repo_url: https://github.com/3dcoded/DynamicMacros
plugins:
  - search
  - autolinks
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
theme:
  features:
      - navigation.indexes
      - navigation.expand
      - navigation.instant
      - navigation.instant.prefetch
      - search.suggest
      - search.highlight
      - search.share
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - tutorial.md
  - devstatus.md