site_name: Klipper Dynamic Macros
site_url: https://3dcoded.github.io/DynamicMacros
repo_url: https://github.com/3dcoded/DynamicMacros
edit_uri: blob/docs/docs/
plugins:
  - search
  - autolinks
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      base_path: docs/snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
extra:
  analytics:
    provider: google
    property: G-1YVCJR4FQR
theme:
  features:
      - content.action.edit
      - navigation.expand
      - navigation.instant
      - navigation.instant.prefetch
      - content.code.copy
      - content.code.annotate
      - search.suggest
      - search.highlight
      - search.share
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - setup.md
  - Tutorial:
    - tutorial/index.md
    - tutorial/converting.md
    - tutorial/usingfeatures.md
    - tutorial/experimental.md
  - Features:
    - features/recursion.md
    - features/receivingvariables.md
    - features/utilities.md
    - features/variables.md
    - features/python.md
    - features/delayed.md
  - Klippy Extras:
    - extras/extras-start.md
    - extras/extras-structure.md
    - extras/extras-bettergreeter.md
  - examples.md
  - devstatus.md