site_name: Klipper Dynamic Macros
site_url: https://3dcoded.github.io/DynamicMacros
repo_url: https://github.com/3dcoded/DynamicMacros
edit_uri: blob/docs/docs/
plugins:
  - search
  - autolinks
  - git-revision-date-localized:
      enable_creation_date: true
  - print-site
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      base_path: docs/snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://3dcoded.github.io
  analytics:
    provider: google
    property: G-1YVCJR4FQR
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/3DCoded/DynamicMacros/issues/new?assignees=&labels=documentation&projects=&template=documentation.md&title=%5BDOCS%5D" target="_blank" rel="noopener">opening an issue</a>.
theme:
  logo: assets/logo.png
  custom_dir: docs/overrides
  features:
      - navigation.tabs
      - content.action.edit
      - navigation.expand
      - navigation.instant
      - navigation.instant.prefetch
      - navigation.footer
      - content.code.copy
      - content.code.annotate
      - search.suggest
      - search.highlight
      - search.share
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - DynamicMacros:
    - setup.md
    - Tutorial:
      - tutorial/index.md
      - tutorial/converting.md
      - tutorial/usingfeatures.md
      - tutorial/experimental.md
    - Features:
      - features/recursion.md
      - features/receivingvariables.md
      - features/utilities.md
      - features/variables.md
      - features/python.md
      - features/delayed.md
      - features/clusters.md
      - features/rendering.md
    - examples.md
    - devstatus.md
  - Klippy Extras:
    - extras/extras-start.md
    - extras/extras-intro.md
    - extras/extras-ex1.md
    - extras/extras-ex2.md
    - extras/extras-ex3.md