site_name: Klipper Dynamic Macros
site_url: https://3dcoded.github.io/DynamicMacros
repo_url: https://github.com/3dcoded/DynamicMacros
edit_uri: blob/docs/docs/
plugins:
  - search
  - autolinks
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
extra:
  analytics:
    provider: google
    property: G-1YVCJR4FQR
theme:
  features:
      - content.action.edit
      - navigation.expand
      - navigation.instant
      - navigation.instant.prefetch
      - content.code.copy
      - search.suggest
      - search.highlight
      - search.share
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - setup.md
  - Tutorial:
    - tutorial/index.md
    - tutorial/converting.md
    - tutorial/usingfeatures.md
    - tutorial/experimental.md
  - Features:
    - features/recursion.md
    - features/receivingvariables.md
    - features/utilities.md
    - features/variables.md
    - features/python.md
    - features/delayed.md
  - examples.md
  - devstatus.md